server {
    listen 443 ssl;    #nginx ecoute sur le port 443 et les communications sont chiffres avec TLS/SSL 
    server_name noakebli.42.fr; #Nginx répond uniquement aux requêtes destinées à https://noakebli.42.fr

    ssl_certificate     /etc/nginx/ssl/inception.crt;      #chemin de certificat public
    ssl_certificate_key /etc/nginx/ssl/inception.key;      #cle privee associe au certificat
    ssl_protocols       TLSv1.2 TLSv1.3;

    root  /var/www/html;                            # repertoire contenant les fichiers du site 
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass            wordpress:9000;
        fastcgi_index           index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
