[mariadbd]

pid-file        = /run/mysqld/mysqld.pid
datadir         = /var/lib/mysql
bind-address    = 0.0.0.0
skip-name-resolve


#desactive la resolution DNS des clients , il utilise uniquement les iP : connexion plus rapide , evite les probleme DNS dans docker.